<?php

namespace Database\Seeders;

use App\Models\Job;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Job::create([
            'name' => 'lorem ipsum',
            'slug' => 'lorem-ipsum-1',
            'extract' => 'lorem ipsum',
            'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p><figure class="image"><img src="http://111-web.test/storage/images/IA1LRDlasAMhGUiTpjvgH5H1n8uqWq8HEqb7ru79.jpg"></figure><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p>',
            'thumbnail' => 'jobs/URgspfyNhBYbW1jwxCBlsaIj819vviLu0zLZmEe6.jpg',
            'banner' => 'jobs/V93QDW2TvOwnDbYkdOl2FbGnGOMDTWXChXbs1kl1.jpg',
            'category_id' => 2,
            'status' => 1,
        ]);
        Job::create([
            'name' => 'lorem ipsum',
            'slug' => 'lorem-ipsum-2',
            'extract' => 'lorem ipsum',
            'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p><figure class="image"><img src="http://111-web.test/storage/images/IA1LRDlasAMhGUiTpjvgH5H1n8uqWq8HEqb7ru79.jpg"></figure><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p>',
            'thumbnail' => 'jobs/URgspfyNhBYbW1jwxCBlsaIj819vviLu0zLZmEe6.jpg',
            'banner' => 'jobs/V93QDW2TvOwnDbYkdOl2FbGnGOMDTWXChXbs1kl1.jpg',
            'category_id' => 1,
            'status' => 1,
        ]);
        Job::create([
            'name' => 'lorem ipsum',
            'slug' => 'lorem-ipsum-3',
            'extract' => 'lorem ipsum',
            'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p><figure class="image"><img src="http://111-web.test/storage/images/IA1LRDlasAMhGUiTpjvgH5H1n8uqWq8HEqb7ru79.jpg"></figure><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p>',
            'thumbnail' => 'jobs/URgspfyNhBYbW1jwxCBlsaIj819vviLu0zLZmEe6.jpg',
            'banner' => 'jobs/V93QDW2TvOwnDbYkdOl2FbGnGOMDTWXChXbs1kl1.jpg',
            'category_id' => 3,
            'status' => 1,
        ]);
        Job::create([
            'name' => 'lorem ipsum',
            'slug' => 'lorem-ipsum-4',
            'extract' => 'lorem ipsum',
            'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p><figure class="image"><img src="http://111-web.test/storage/images/IA1LRDlasAMhGUiTpjvgH5H1n8uqWq8HEqb7ru79.jpg"></figure><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p>',
            'thumbnail' => 'jobs/URgspfyNhBYbW1jwxCBlsaIj819vviLu0zLZmEe6.jpg',
            'banner' => 'jobs/V93QDW2TvOwnDbYkdOl2FbGnGOMDTWXChXbs1kl1.jpg',
            'category_id' => 1,
            'status' => 1,
        ]);
        Job::create([
            'name' => 'lorem ipsum',
            'slug' => 'lorem-ipsum-5',
            'extract' => 'lorem ipsum',
            'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p><figure class="image"><img src="http://111-web.test/storage/images/IA1LRDlasAMhGUiTpjvgH5H1n8uqWq8HEqb7ru79.jpg"></figure><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p>',
            'thumbnail' => 'jobs/URgspfyNhBYbW1jwxCBlsaIj819vviLu0zLZmEe6.jpg',
            'banner' => 'jobs/V93QDW2TvOwnDbYkdOl2FbGnGOMDTWXChXbs1kl1.jpg',
            'category_id' => 4,
            'status' => 1,
        ]);
        Job::create([
            'name' => 'lorem ipsum',
            'slug' => 'lorem-ipsum-6',
            'extract' => 'lorem ipsum',
            'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p><figure class="image"><img src="http://111-web.test/storage/images/IA1LRDlasAMhGUiTpjvgH5H1n8uqWq8HEqb7ru79.jpg"></figure><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p>',
            'thumbnail' => 'jobs/URgspfyNhBYbW1jwxCBlsaIj819vviLu0zLZmEe6.jpg',
            'banner' => 'jobs/V93QDW2TvOwnDbYkdOl2FbGnGOMDTWXChXbs1kl1.jpg',
            'category_id' => 3,
            'status' => 1,
        ]);
        Job::create([
            'name' => 'lorem ipsum',
            'slug' => 'lorem-ipsum-7',
            'extract' => 'lorem ipsum',
            'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p><figure class="image"><img src="http://111-web.test/storage/images/IA1LRDlasAMhGUiTpjvgH5H1n8uqWq8HEqb7ru79.jpg"></figure><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vulputate nunc orci, nec laoreet orci lobortis a. Quisque tincidunt massa quis consectetur fermentum. Donec semper posuere eros eu malesuada. Vestibulum varius vehicula auctor. Proin varius, mauris quis bibendum egestas, purus massa ultricies orci, aliquam ultricies libero dolor sed dolor. Phasellus et vestibulum est. Vestibulum dignissim, ligula vel iaculis maximus, diam lacus accumsan est, ut accumsan nisi orci eget sapien. Vivamus egestas, nunc in laoreet scelerisque, dui ligula elementum nunc, ut mollis ante risus et elit. Aliquam vitae finibus turpis. Sed fringilla vestibulum risus sit amet malesuada. Vivamus vitae est dolor. Ut molestie bibendum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur orci et ligula ultricies suscipit. Vivamus quis libero ligula.</p><p>Vestibulum blandit quam vitae magna blandit accumsan. Ut suscipit in nisi eget finibus. Fusce semper ultrices tincidunt. Pellentesque ultrices mi eu tincidunt efficitur. Sed nec ex risus. Nam tristique lacus in dignissim finibus. Donec sagittis nunc a diam mollis, id congue nulla dapibus. Maecenas sed iaculis eros, eu sollicitudin sapien. Sed sollicitudin elit eget nisi porttitor hendrerit vitae ut lorem.</p>',
            'thumbnail' => 'jobs/URgspfyNhBYbW1jwxCBlsaIj819vviLu0zLZmEe6.jpg',
            'banner' => 'jobs/V93QDW2TvOwnDbYkdOl2FbGnGOMDTWXChXbs1kl1.jpg',
            'category_id' => 1,
            'status' => 1,
        ]);
    }
}
